test_homepage:
    path:     /
    defaults: { _controller: TestBundle:Poker:index }

token:
    path:     /token
    defaults: { _controller: TestBundle:Poker:getToken }

check-winner:
    path:    /check-winner
    defaults: { _controller: TestBundle:Poker:checkWinner }
    options:
            expose: true